### ISSUE TITLE
Package Installation Errors

### ISSUE THREAD

**Issue by natebunton** [ligershark/template-builder#48]
When I try to install the TemplateBuilder package I get errors...

PM> install-package TemplateBuilder -pre
Installing 'TemplateBuilder 1.0.3.47-beta'.
Successfully installed 'TemplateBuilder 1.0.3.47-beta'.
Adding 'TemplateBuilder 1.0.3.47-beta' to VSIXProject2.
Successfully added 'TemplateBuilder 1.0.3.47-beta' to VSIXProject2.
*********** Adding template-builder
	Adding item template asset tag to .vsixmanifest file c:\users\nbunton\documents\visual studio 2013\Projects\VSIXProject2\VSIXProject2\source.extension.vsixmanifest
Method invocation failed because [System.Object[]] doesn't contain a method named 'AppendChild'.
At C:\users\nbunton\documents\visual studio 2013\Projects\VSIXProject2\packages\TemplateBuilder.1.0.3.47-beta\tools\template-builder.psm1:185 char:65
+         (GetOrCreateAssetsElement -vsixXml $vsixXml).AppendChild <<<< ($newElement)
    + CategoryInfo          : InvalidOperation: (AppendChild:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
 
	Adding project template asset tag to .vsixmanifest file c:\users\nbunton\documents\visual studio 2013\Projects\VSIXProject2\VSIXProject2\source.extension.vsixmanifest
Method invocation failed because [System.String] doesn't contain a method named 'AppendChild'.
At C:\users\nbunton\documents\visual studio 2013\Projects\VSIXProject2\packages\TemplateBuilder.1.0.3.47-beta\tools\template-builder.psm1:226 char:65
+         (GetOrCreateAssetsElement -vsixXml $vsixXml).AppendChild <<<< ($newElement)
    + CategoryInfo          : InvalidOperation: (AppendChild:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
 
    TemplateBuilder has been installed into project [c:\users\nbunton\documents\visual studio 2013\Projects\VSIXProject2\VSIXProject2\VSIXProject2.csproj]
    
For more info how to enable TemplateBuilder on build servers see http://sedodream.com/2013/06/06/HowToSimplifyShippingBuildUpdatesInANuGetPackage.aspx

**Comment by domholmes** [comment]
@sayedihashimi I updated the .vsixmanifest with Asset lines mentioned in the readme and completed the rest of the steps in the tutorial, but nothing shows in the list of templates when debugging.

My file structure is identical to the tutorial, any ideas how to debug what is wrong?

![image](https://cloud.githubusercontent.com/assets/3393862/6214343/b3b14812-b5ef-11e4-8202-ba71ec339531.png)


Thanks

**Comment by RandomlyKnighted** [comment]
@domholmes The definition files are created that way because SideWaffle adds a vstemplate file for each supported language. You have to rename the files of the languages you want your template to support. Until this is done, the vstemplate file will remain disabled. It's just a simple way of adding all the vstemplate files you might possibly need then letting you select the ones you want.

@natebunton I know your original post was almost a year ago, but I just wanted to check to see if you were able to come up with a workaround? If not, then I recommend updating to version 1.1.3 of TemplateBuilder, which was just released the other day.

**Comment by natebunton** [comment]
I have not tried recently. I will have to try the latest release. 

- Nate

**Comment by sayedihashimi** [comment]
It should be fixed in the latest release. Please reopen if not.
