### ISSUE TITLE
Project built from template defaults to using IIS Express

### ISSUE THREAD

**Issue by seancostigan** [ligershark/template-builder#65]
I upgraded my template project from template-builder v. 1.0.3.47-beta to v. 1.1.3.  I am able to build my VSIX, however when I create a new project using the template, it always defaults to using IIS Express.  I have configured the template project to use Local IIS (on the Web tab in the project properties).  This does not happen with 1.0.3.47-beta, the Local IIS setting is correctly carried over from the template project to the new project.

![properties](https://cloud.githubusercontent.com/assets/11294786/6463545/07a89c62-c181-11e4-98b9-25f5ec893d84.png)

**Comment by RandomlyKnighted** [comment]
@sayedihashimi have there been any changes to TemplateBuilder that should affect which web server is default for a template?

**Comment by sayedihashimi** [comment]
I introduced a change to remove the ```ProjectExtensions``` element when the template is built in this commit https://github.com/ligershark/template-builder/commit/7629723307fc7f32df03a120712b9dee0f04f74a. You can disable this in the ```.props``` file under ```Properties``` by adding the following property.

```
<ls-enable-remove-proj-extensions>false</ls-enable-remove-proj-extensions>
```

If it doesn't work for you please re-open.
