### ISSUE TITLE
.csproj.user and IIS Express

### ISSUE THREAD

**Issue by frialex** [ligershark/template-builder#69]
My problem is that I want to create a template that will use IIS instead of IIS Express. I'm doing this because I want the newly created project to be a child app of an already established site. This established site will provide common Javascript and css for all child apps, along with a few HTTP endpoints. This hierarchy is there to prevent cross-domain rules from being applied on ajax requests.

The reason I don't want to mix IIS Express with IIS is due to port issues (one of them gotta run in a different port, thereby causing IE to apply cross-domain rules in ajax and breaking application). The second reason is consistency. I've ran in to inconsistent behaviors between the two in the past.

The crux of the problem is that visual studio puts the web server config settings in .csproj file. I'm not sure of the reason why .csproj is in the preprocess exclude group, but it does make sense since visual studio will give you a new csproj file with settings that are different than from what is in the template.

My first step was to put the IIS settings in .csproj.user file, and manually edit .csproj file to include the .user file as part of the template... But now the problem is to transform file names: Template.csproj.user to InstnceOfTemplate.csproj.user... This doesn't seem like a good way to go.

So now that dealing with .csproj files are out (or if you know of something that I've missed they are back in), I'm looking at other way to configure the project after creation.

During my research I've found that NuGet packages are able to run powershell scripts after they have been installed on to the project, so that kinda opens doors.. but those doors should have never been there in the first place.

It seems that you have something similar via  Package class in the VSPackage project... and I'm going to explore that next. 

But before I start exploring..
It look like I'm missing out on some information. 

#### Create an instance of the template that is EXACTLY like the template. If I've set up the template to use IIS then the instance should also use IIS. The ONLY difference being namespaces.

Any comments/Ideas?

**Comment by sayedihashimi** [comment]
>I'm not sure of the reason why .csproj is in the preprocess exclude group

That's a bug, it should be removed. I created #70 to track it. I'll take care of it. In the meantime you can just remove it from your _preprocess.xml file.

If you do that does your template work as expected or is there more that needs to be done? FYI the .user file is special and it's created by the project system itself. I don't think that it will work if you add a .csproj.user file to your template, but not 100% sure.

**Comment by frialex** [comment]
Hey, Thanks for the quick reply!

My initial observation was that visual studio is providing a .csproj file, even though *.csproj is removed from the exclude group. 

To verify this I added a property group to the templates .csproj file. This property group is not present in the instance of the template created by visual studio. Furthermore, the .csproj file in the instance is the EXACT some one provided when a new MVC application is created, which uses IIS Express.

These tests were run on Windows 7, Visual Studio Pro 12.0.31101.00 Update 4.  To create an instance of the template, I cleaned, built and hit start debugging on the solution containing the VSPackage.

### Template's .csproj file
![image](https://cloud.githubusercontent.com/assets/1047886/8354103/3fc58132-1b13-11e5-9be8-e5aaf5ef4dad.png)

### Template's configuration selection dialog
![image](https://cloud.githubusercontent.com/assets/1047886/8354136/8dd958c6-1b13-11e5-88b1-ddcc6f010293.png)

### .csproj of the newly created instance of the template
![image](https://cloud.githubusercontent.com/assets/1047886/8354182/f39e4e1e-1b13-11e5-93a6-8e6674c60c03.png)

### configuration dialog of the instance
![image](https://cloud.githubusercontent.com/assets/1047886/8354199/1d90c51c-1b14-11e5-881f-38e7d9fb70ec.png)

**Comment by RandomlyKnighted** [comment]
This should be fixed in the recent versions of TemplateBuilder. If you continue to have issues, feel free to reopen.
