### ISSUE TITLE
DNX Projects - Web, and Packages

### ISSUE THREAD

**Issue by Antaris** [ligershark/template-builder#83]
Hi,

I'm looking to build some project (ideally solution templates). Is this possible?

I'd like to generate a solution structure with:

src/DNXProject/DNXProject.xproj
src/DNXProject/project.json
test/DNXProject.Tests/DNXProject.xproj
test/DNXProject.Tests/project.json
global.json
NuGet.config

I've started with generating a basic project, but in DNX-based projects, there are no file references in the `xproj` file, because it's a directory based solution, so when the project template is initialised in the Experimental instance, there are no files included.

**Comment by RandomlyKnighted** [comment]
TemplateBuilder is the library we use to make SideWaffle work. On our main SideWaffle repo, there is a [Wiki article](https://github.com/ligershark/side-waffle/wiki/How-to-create-templates-for-ASP.NET-5) that talks about creating ASP.NET 5 templates. I believe that is what you are looking for. Please let us know if you run into any issues. Check that out and please let us know if run into issues. I'm going to close this for now. If you do run into any issues, please open the issue in the main SideWaffle repo. Thanks!
