### ISSUE TITLE
folder exclusion?

### ISSUE THREAD

**Issue by QHQuach** [ligershark/template-builder#93]
Is there a way to specify for specific folder exclusion (e.g. node_modules and bower_component) in vsix build (ASP.NET Core xproj template)? The reason is that our team has large usage of these 2 packaging mechanism and it is causing length vsix build as well as large size vsix file.

**Comment by sayedihashimi** [comment]
I don't think it's possible. Instead of using template builder for this I have a new technique, see my video https://github.com/ligershark/side-waffle/issues/379.

Fyi please open issues in the SideWaffle repo, we have more eyes there.
