### ISSUE TITLE
Question: Is there a simple way using this to add a project reference from one project to another?

### ISSUE THREAD

**Issue by awright18** [ligershark/template-builder#95]
s there a simple way using this to add a project reference from one project to another?

If I have project template A and project template B.
I want to add a reference to project A in project B, at some point during the template creation.  Does this help with that?  I can access the project A name, but don't know how to get the GUID.  Thanks.

**Comment by sayedihashimi** [comment]
I'm not really following the question here but it sounds like you want to create a project and also add a ref to the new project in another project? If so you'll need a custom wizard.

**Comment by awright18** [comment]
You followed exactly, I assumed that is the most common scenario for a multi project template, but I could be wrong.  I'll see if I can figure it out.  Thanks for your time.
