### ISSUE TITLE
Support Visual Studio 2017 .NET Core csproj Projects

### ISSUE THREAD

**Issue by RehanSaeed** [ligershark/template-builder#96]
I get the following error for every NuGet package in my template project (.NET Core csproj) while trying to build my VSIX using Visual Studio:

>C:\GitHub\Templates\packages\TemplateBuilder.1.1.4.9-beta\tools\ligershark.templates.targets(532,5): error MSB3030: Could not copy the file "C:\GitHub\Templates\Source\MVC6\Boilerplate.AspNetCore.Sample\Microsoft.Extensions.Configuration.CommandLine" because it was not found.

@RandomlyKnighted Any ideas if the new format is supported.

**Comment by sayedihashimi** [comment]
@RehanSaeed can you share a sample?

**Comment by RehanSaeed** [comment]
I have a [branch](https://github.com/ASP-NET-MVC-Boilerplate/Templates/tree/VS-2017). Just try opening the solution and building.

**Comment by RehanSaeed** [comment]
I should mention, I get one error per package reference in my csproj.

**Comment by RehanSaeed** [comment]
Doing some more investigation, I looked at the section in `ligershark.templates.targets(532,5)` causing the problem:

```
    <!-- TODO: now that we are copying the entire folder I think this step can be removed -->
    <Copy SourceFiles="@(_ls-NewProjFilesToCopyRaw->'$(_ls-TemplateFolder2)%(Identity)')"
          DestinationFiles="@(_ls-NewProjFilesToCopyRaw->'$(ls-DestTemplateOutputRoot)%(Identity)')">
      <Output TaskParameter ="CopiedFiles" ItemName="ls-temp-FilesCopied"/>
    </Copy>
```

I'm not sure what these lines do. The [comment](https://github.com/ligershark/template-builder/commit/f67c6076c09a9d7c81017388a2e53ca2be150327) added by @sayedihashimi suggests that it's not needed, so I tried removing it and I was able to build a VSIX again. I've not validated the VSIX works yet as I've run out of time but it does contain my projects.

**Comment by sayedihashimi** [comment]
Yes I looked at that a while ago and I'm pretty sure we can remove that. Can you verify and send a PR? I'll release an update.

**Comment by RehanSaeed** [comment]
@sayedihashimi I just tested removing those lines:

1. MVC 5 project creation is fine.
2. .NET Core VS 2017 csproj project shows the following error dialog for each NuGet package installed in the project and then when the project is finally created, it is completely empty apart from the ReadMe.html file which opens.

![untitled](https://cloud.githubusercontent.com/assets/2270364/23553548/2622cea0-0019-11e7-9182-bb85371b423c.png)

**Comment by sayedihashimi** [comment]
How about non core projects?  This could be a bug in the Roslyn project system.

**Comment by RehanSaeed** [comment]
My MVC 5 project (non .NET Core) gets created just fine.

**Comment by sayedihashimi** [comment]
@RehanSaeed can you share the .vsix which shows this behavior?

**Comment by RehanSaeed** [comment]
@sayedihashimi Here is a link to my VSIX on MyGet:
https://www.myget.org/feed/aspnet-mvc-boilerplate/package/vsix/MvcBoilerplateVsix.Microsoft.dafd466d-39dc-487e-846b-7cf0e569821c/6.0.0

**Comment by RehanSaeed** [comment]
@sayedihashimi Any clues what might be causing this? Anything I can take a look at? I realize you were probably busy with the VS 2017 launch.

**Comment by RehanSaeed** [comment]
Raised this PR to fix this issue: https://github.com/ligershark/template-builder/pull/98

**Comment by shanselman** [comment]
:(

**Comment by RehanSaeed** [comment]
@shanselman Nice to see you share my pain. Building a VSIX is extremely frustrating process, every VS upgrade breaks something. Would like to move to `dotnet new` but VS is where the users are at. `dotnet new` could **really** use a UI in Visual Studio.

**Comment by RehanSaeed** [comment]
Have raised [Build a UI in Visual Studio for dotnet new Templates](https://github.com/dotnet/templating/issues/481) as an issue.

**Comment by RehanSaeed** [comment]
@sayedihashimi Congrats on the baby, it takes about a year to get some sleep :)

Merged into master. I'm planning to release a hacked together VSIX (builds on my machine using VS but not AppVeyor using MSBuild) that shows a message box telling the developer to expect VS to crash and to just reopen the solution. Not ideal but at least I can release something.

**Comment by sayedihashimi** [comment]
@RehanSaeed I've merged your PR and released it as `TemplateBuilder.1.1.5-beta.nupkg`. In that release I also made another [minor change](https://github.com/ligershark/template-builder/commit/c566214ef19b8eceab996e70e2760109800db711). When the .vstemplate file was being generated there were two `ProjectItem`s listed
 - `Microsoft.ApplicationInsights.AspNetCore`
 - `Microsoft.AspNetCore`

Those files must be coming in from .net core .targets/.props files but I haven't figured out which one yet. For now I've just special cased them and explicitly excluded them. If you see the same issue in your hacked version you can add those values to the `ls-ProjectTemplateFilesToRemoveOnCopy` item and you don't need to update the .targets file.

About the issue you mentioned about not being able to build the .vsix. I created a new vsix project in VS for testing templates and I was able to build the vsix with the following command. I think maybe `-visualStudioVersion` is the missing property that you should add but not sure. Also check to make sure you are building with the correct `msbuild.exe`.

```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" ".\VSIXProject1\VSIXProject1.csproj" /p:VisualStudioVersion=15.0 /m
```

I'm still looking into this issue. Will reply back here when I get more info to share.

**Comment by RehanSaeed** [comment]
Thanks for that!

# Issue 1 Fixed

A lot of people are getting the `error VSSDK1081: Problem occurred while extracting the vsix to the experimental extensions path.` error. See [MSDN](https://social.msdn.microsoft.com/Forums/en-US/7c4c9766-9ac4-4681-851d-7c69c4a73b57/problem-occurred-extracting-the-vsix-to-the-experimental-instance?forum=vsx) and https://github.com/Microsoft/extendvs/issues/41. It's hitting the 254 file path length limit in .NET. The solution is to use a short product title, publisher name and template name (Not ideal).

# Issue 2 Fixed

Thanks for that, I can do CI again! Your secret MSBuild argument `/p:VisualStudioVersion=15.0` got it building.

# Issue 3 Remains

I still get the following exception when overwriting files in the project when applying the users feature selections:

```
System.ObjectDisposedException occurred
  HResult=0x80131622
  Message=Cannot access a disposed object.
  Source=Microsoft.VisualStudio.Validation
  StackTrace:
   at Microsoft.Verify.NotDisposed(IDisposableObservable disposedValue, String message)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposed.EnsureInitialized(Boolean allowInitializing)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.SubmitTreeUpdateAsync(TreeUpdateAsyncDelegate treeTransformation, IImmutableDictionary`2 updatedSources, TreeSubmissionOptions options, Int64& generationNumber, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesProjectTreeProvider.OnDependenciesChanged(Object sender, DependenciesChangedEventArgs e)
   at Microsoft.VisualStudio.Web.PackageManagement.SolutionExplorer.ProjectDependenciesAdapterBase.OnDependenciesChanged(DependenciesChangedEventArgs args)
   at Microsoft.VisualStudio.Web.PackageManagement.SolutionExplorer.ProjectDependenciesAdapterBase.InvalidateGraph(Object sender, EventArgs e)
   at Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmPackageProvider.FirePackagesChanged()
   at Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmPackageProvider.<RefreshRootNode>d__55.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.PackageManagement.Utilities.BatchingTaskScheduler.<Invoke>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by RehanSaeed** [comment]
Released an update. Issue 3 seems to be gone the last time I tried after updating VS. Will create a new VS tooling issue if it re-occurs.
